version: "3.7"
services:
  eatery_api:
    container_name: eatery_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - eatery_db
    networks:
      - app_network

  eatery_nginx:
    container_name: eatery_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - eatery_api
    environment:
      NGINX_FPM_HOST: eatery_api
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  eatery_db:
    container_name: eatery_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: eatery
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  eatery_redis:
    container_name: eatery_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
